CREATE TABLE IF NOT EXISTS glass
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(50)   NOT NULL,
    description VARCHAR(2000) NOT NULL,
    CONSTRAINT pk_glass PRIMARY KEY (id)
);


CREATE TABLE IF NOT EXISTS cocktail
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(50)   NOT NULL,
    volume      INTEGER       NOT NULL,
    abv         DECIMAL(5, 2) NOT NULL,
    description VARCHAR(2000) NOT NULL,
    recipe      VARCHAR(2000) NOT NULL,
    CONSTRAINT pk_cocktail PRIMARY KEY (id)
);


CREATE TABLE IF NOT EXISTS cocktail_glass
(
    cocktail_name VARCHAR     NOT NULL,
    glass_name    VARCHAR     NOT NULL,
    CONSTRAINT pk_cocktail_glass PRIMARY KEY (cocktail_name, glass_name)
);


CREATE TABLE IF NOT EXISTS ingredient
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(50)   NOT NULL,
    abv         DECIMAL(5, 2) NOT NULL,
    category    VARCHAR(255),
    description VARCHAR(2000) NOT NULL,
    CONSTRAINT pk_ingredient PRIMARY KEY (id)
);


CREATE TABLE IF NOT EXISTS cocktail_ingredient
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    cocktail_name   VARCHAR      NOT NULL,
    ingredient_name VARCHAR      NOT NULL,
    amount          VARCHAR(20)  NOT NULL,
    CONSTRAINT pk_cocktailIngredient PRIMARY KEY (id)
);


ALTER TABLE cocktail
    ADD CONSTRAINT uc_cocktail_name UNIQUE (name);

ALTER TABLE glass
    ADD CONSTRAINT uc_glass_name UNIQUE (name);

ALTER TABLE ingredient
    ADD CONSTRAINT uc_ingredient_name UNIQUE (name);

ALTER TABLE cocktail_ingredient
    ADD CONSTRAINT fk_cocktailIngredient_on_cocktail_name FOREIGN KEY (cocktail_name) REFERENCES cocktail (name);

ALTER TABLE cocktail_ingredient
    ADD CONSTRAINT fk_cocktailIngredient_on_ingredient_name FOREIGN KEY (ingredient_name) REFERENCES ingredient (name);

ALTER TABLE cocktail_glass
    ADD CONSTRAINT fk_cocktailGlass_on_cocktail FOREIGN KEY (cocktail_name) REFERENCES cocktail (name);

ALTER TABLE cocktail_glass
    ADD CONSTRAINT fk_cocktailGlass_on_glass FOREIGN KEY (glass_name) REFERENCES glass (name);